---
language: node_js
node_js:
  - "0.12.15"

sudo: false

before_install:
  - npm config set spin false
  - npm install -g npm@^2

before_script:
  - npm install -g typescript
  - npm install -g tslint
  - npm install -g csslint

script:
  - ./lint.sh
