---
language: node_js
node_js:
  - "0.12.15"

sudo: false

before_install:
  - npm config set spin false
  - npm install -g npm@^2

install:
  - npm install -g typescript
  - npm install -g tslint
  - npm install -g csslint
  - npm install -g jsonlint

before_script:
  - ./lint.sh

script:
  - tsc -p tsconfig.json
